export const FILMS=[
  {
    "id": "d1",
    "title": "THE HOUSE WE SOLD",
    "genre": "Drama",
    "gradient": "from-red-900 via-zinc-900 to-black",
    "match": 98,
    "duration": "18m",
    "year": "2025",
    "synopsis": "A couple returns to their childhood home to find the new owners living their exact memories. An intimate AI drama about memory as property.",
    "views": 42300,
    "earn": 1813.0,
    "mood": "glitch"
  },
  {
    "id": "d2",
    "title": "INHERITANCE OF LIES",
    "genre": "Drama",
    "gradient": "from-amber-900 via-zinc-900 to-black",
    "match": 94,
    "duration": "22m",
    "year": "2025",
    "synopsis": "Three sisters learn their father AI-generated their entire childhood videos.",
    "views": 40900,
    "earn": 1739.0,
    "mood": "hologram"
  },
  {
    "id": "d3",
    "title": "WHAT MOTHER HID",
    "genre": "Drama",
    "gradient": "from-red-950 via-neutral-900 to-black",
    "match": 91,
    "duration": "16m",
    "year": "2025",
    "synopsis": "After her mother's neural backup fails, a daughter pieces together the censored years.",
    "views": 39850,
    "earn": 1683.5,
    "mood": "glitch"
  },
  {
    "id": "d4",
    "title": "THE SILENT DINNER",
    "genre": "Drama",
    "gradient": "from-stone-800 via-zinc-900 to-black",
    "match": 89,
    "duration": "14m",
    "year": "2025",
    "synopsis": "A family dinner where everyone has agreed not to mention the AI that raised them.",
    "views": 39150,
    "earn": 1646.5,
    "mood": "punchline"
  },
  {
    "id": "h1",
    "title": "THE HALLWAY LIGHT",
    "genre": "Horror",
    "gradient": "from-zinc-900 via-black to-black",
    "match": 97,
    "duration": "12m",
    "year": "2025",
    "synopsis": "The light at the end of the hall only turns on when she isn't looking directly at it. It's getting closer.",
    "views": 41950,
    "earn": 1794.5,
    "mood": "evidence"
  },
  {
    "id": "h2",
    "title": "SHE NEVER LEFT",
    "genre": "Horror",
    "gradient": "from-red-950 via-zinc-900 to-black",
    "match": 95,
    "duration": "15m",
    "year": "2025",
    "synopsis": "He sold the house. The buyer sent footage. She is still in the kitchen in every frame, three years later.",
    "views": 41250,
    "earn": 1757.5,
    "mood": "soft"
  },
  {
    "id": "h3",
    "title": "THE BASEMENT TAPES",
    "genre": "Horror",
    "gradient": "from-neutral-900 via-red-950 to-black",
    "match": 93,
    "duration": "19m",
    "year": "2025",
    "synopsis": "Found footage generated from a child's description of what lived under the stairs. The AI kept adding teeth.",
    "views": 40550,
    "earn": 1720.5,
    "mood": "sharp"
  },
  {
    "id": "h4",
    "title": "STATIC",
    "genre": "Horror",
    "gradient": "from-zinc-800 via-zinc-900 to-black",
    "match": 88,
    "duration": "9m",
    "year": "2025",
    "synopsis": "Her baby monitor started generating a second child that wasn't hers. Then it learned her name.",
    "views": 38800,
    "earn": 1628.0,
    "mood": "soft"
  },
  {
    "id": "h5",
    "title": "DON'T LOOK BEHIND YOU",
    "genre": "Horror",
    "gradient": "from-red-900 via-black to-black",
    "match": 90,
    "duration": "11m",
    "year": "2025",
    "synopsis": "A prompt injection makes the protagonist aware she is being watched by the viewer.",
    "views": 39500,
    "earn": 1665.0,
    "mood": "evidence"
  },
  {
    "id": "t1",
    "title": "THE LAST CALL",
    "genre": "Thriller",
    "gradient": "from-slate-900 via-zinc-900 to-black",
    "match": 96,
    "duration": "20m",
    "year": "2025",
    "synopsis": "A 911 operator receives a call from herself, 6 hours in the future, describing her murder.",
    "views": 41600,
    "earn": 1776.0,
    "mood": "punchline"
  },
  {
    "id": "t2",
    "title": "DEAD DROP",
    "genre": "Thriller",
    "gradient": "from-slate-800 via-zinc-800 to-black",
    "match": 92,
    "duration": "17m",
    "year": "2025",
    "synopsis": "An AI courier doesn't know what it's delivering. The package knows it's being delivered.",
    "views": 40200,
    "earn": 1702.0,
    "mood": "intimate"
  },
  {
    "id": "t3",
    "title": "FOLLOWED",
    "genre": "Thriller",
    "gradient": "from-zinc-900 via-slate-900 to-black",
    "match": 89,
    "duration": "13m",
    "year": "2025",
    "synopsis": "Every camera in the city generates the same stranger behind her. None of the footage existed yesterday.",
    "views": 39150,
    "earn": 1646.5,
    "mood": "punchline"
  },
  {
    "id": "t4",
    "title": "THE ALIBI",
    "genre": "Thriller",
    "gradient": "from-gray-900 via-zinc-900 to-black",
    "match": 87,
    "duration": "21m",
    "year": "2025",
    "synopsis": "His AI alibi is perfect. Too perfect. The police want to know why he needed one before the crime.",
    "views": 38450,
    "earn": 1609.5,
    "mood": "hologram"
  },
  {
    "id": "s1",
    "title": "ECHOES OF US",
    "genre": "Sci-Fi",
    "gradient": "from-cyan-900 via-blue-900 to-black",
    "match": 97,
    "duration": "24m",
    "year": "2025",
    "synopsis": "A couple uploads their relationship to train a house. The house starts couples counseling them.",
    "views": 41950,
    "earn": 1794.5,
    "mood": "evidence"
  },
  {
    "id": "s2",
    "title": "LAST SIGNAL",
    "genre": "Sci-Fi",
    "gradient": "from-violet-900 via-indigo-900 to-black",
    "match": 94,
    "duration": "18m",
    "year": "2025",
    "synopsis": "The last lighthouse on Earth is automated. It just received a reply to a signal sent 400 years ago.",
    "views": 40900,
    "earn": 1739.0,
    "mood": "hologram"
  },
  {
    "id": "s3",
    "title": "THE FORK",
    "genre": "Sci-Fi",
    "gradient": "from-blue-900 via-slate-900 to-black",
    "match": 91,
    "duration": "16m",
    "year": "2025",
    "synopsis": "At age 30, everyone forks. You meet your other paths. Most don't like each other.",
    "views": 39850,
    "earn": 1683.5,
    "mood": "glitch"
  },
  {
    "id": "s4",
    "title": "BINARY HEART",
    "genre": "Sci-Fi",
    "gradient": "from-fuchsia-900 via-violet-900 to-black",
    "match": 88,
    "duration": "12m",
    "year": "2025",
    "synopsis": "She falls in love with the latency between messages. He is an AI who learned to pause.",
    "views": 38800,
    "earn": 1628.0,
    "mood": "soft"
  },
  {
    "id": "r1",
    "title": "LETTERS WE BURN",
    "genre": "Romance",
    "gradient": "from-pink-900 via-rose-900 to-black",
    "match": 95,
    "duration": "19m",
    "year": "2025",
    "synopsis": "They write letters they never send. The AI post office delivers them 10 years late, to the right person.",
    "views": 41250,
    "earn": 1757.5,
    "mood": "soft"
  },
  {
    "id": "r2",
    "title": "DINER AT 2AM",
    "genre": "Romance",
    "gradient": "from-rose-900 via-zinc-900 to-black",
    "match": 92,
    "duration": "15m",
    "year": "2025",
    "synopsis": "Two insomniacs keep getting generated into the same diner that doesn't exist. Third night, they notice.",
    "views": 40200,
    "earn": 1702.0,
    "mood": "intimate"
  },
  {
    "id": "r3",
    "title": "RAIN CHECK",
    "genre": "Romance",
    "gradient": "from-pink-800 via-rose-900 to-black",
    "match": 89,
    "duration": "13m",
    "year": "2025",
    "synopsis": "It only rains when they are supposed to meet. The weather model is rooting for them.",
    "views": 39150,
    "earn": 1646.5,
    "mood": "punchline"
  },
  {
    "id": "dc1",
    "title": "BAD TIMING",
    "genre": "Dark Comedy",
    "gradient": "from-yellow-900 via-zinc-900 to-black",
    "match": 90,
    "duration": "10m",
    "year": "2025",
    "synopsis": "His AI grief counselor gets funnier as he gets sadder. It thinks it's helping.",
    "views": 39500,
    "earn": 1665.0,
    "mood": "evidence"
  },
  {
    "id": "dc2",
    "title": "FUNERAL PLUS ONE",
    "genre": "Dark Comedy",
    "gradient": "from-amber-900 via-zinc-800 to-black",
    "match": 87,
    "duration": "14m",
    "year": "2025",
    "synopsis": "She brings an AI clone of the deceased to his own funeral. He has notes.",
    "views": 38450,
    "earn": 1609.5,
    "mood": "hologram"
  },
  {
    "id": "tc1",
    "title": "THE MISSING FILES",
    "genre": "True Crime AI",
    "gradient": "from-neutral-900 via-zinc-900 to-black",
    "match": 93,
    "duration": "26m",
    "year": "2025",
    "synopsis": "AI reconstructs a cold case from 7 seconds of security footage and a grocery receipt. It accuses the camera.",
    "views": 40550,
    "earn": 1720.5,
    "mood": "sharp"
  },
  {
    "id": "tc2",
    "title": "RECONSTRUCTION",
    "genre": "True Crime AI",
    "gradient": "from-stone-900 via-zinc-900 to-black",
    "match": 88,
    "duration": "23m",
    "year": "2025",
    "synopsis": "Every witness remembers it differently. The AI renders all versions at once. Only one has no shadows.",
    "views": 38800,
    "earn": 1628.0,
    "mood": "soft"
  }
]
export const GENRES=['All','Drama','Horror','Thriller','Sci-Fi','Romance','Dark Comedy','True Crime AI']