
-- RUN THIS IN SUPABASE SQL EDITOR - FULL PRODUCTION
create table if not exists films (
  id text primary key,
  title text not null,
  genre text not null,
  synopsis text,
  prompt text,
  video_url text not null,
  poster text,
  duration text default '18m',
  views int default 0,
  likes int default 0,
  featured_score numeric default 100,
  match int default 95,
  status text default 'live' check (status in ('live','featured','scheduled','archived')),
  scheduled_release_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  is_real_ai boolean default false
);

create table if not exists profiles (
  id uuid primary key references auth.users(id),
  email text,
  stripe_customer_id text,
  subscription_status text default 'free' check (subscription_status in ('free','active','canceled','past_due')),
  stripe_subscription_id text,
  created_at timestamp default now()
);

-- Enable RLS
alter table films enable row level security;
alter table profiles enable row level security;
create policy "public read live films" on films for select using (status in ('live','featured'));
create policy "admin all" on films for all using (true);
create policy "profiles self" on profiles for all using (auth.uid() = id);

-- Insert 24 REAL AI FILM PROMPTS - Will be generated by bot
delete from films;
insert into films (id, title, genre, synopsis, prompt, video_url, poster, duration, views, match, featured_score, status, is_real_ai) values
('drama-1','THE HOUSE WE SOLD','Drama','A couple returns to childhood home to find new owners living their exact memories.','Cinematic drama, couple returns to childhood home, new owners living their exact memories, intimate, 4k, film grain, A24 style, shallow depth of field','https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600', '18m', 42300, 98, 450, 'featured', false),
('drama-2','INHERITANCE OF LIES','Drama','Three sisters learn their father AI-generated their entire childhood videos.','Three sisters watching old home videos glitching, realizing father AI generated childhood, dramatic revelation, cinematic','https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4','https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600','22m', 40900, 94, 400, 'featured', false),
('drama-3','WHAT MOTHER HID','Drama','After mother neural backup fails, daughter pieces together censored years.','Daughter piecing together mother neural backup failure, censored memories, emotional sci-fi drama','https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4','https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600','16m', 39850, 91, 380, 'live', false),
('drama-4','THE SILENT DINNER','Drama','Family dinner where everyone agreed not to mention AI that raised them.','Tense family dinner, everyone avoiding mentioning AI that raised them, subtle sci-fi drama, cinematic','https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600','14m', 39150, 89, 320, 'live', false),
('horror-1','THE HALLWAY LIGHT','Horror','Light at end of hall only turns on when she is not looking directly at it. Getting closer.','Psychological horror, hallway light turns on when not looking, getting closer each time, atmospheric, dark','https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4','https://images.unsplash.com/photo-1509248961158-e32a2f3d92bb?w=600','12m', 41950, 97, 420, 'featured', false),
('horror-2','SHE NEVER LEFT','Horror','He sold house. Buyer sent footage. She is still in kitchen in every frame, 3 years later.','Found footage horror, woman still in kitchen in every frame after house sold, unsettling, VHS style','https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4','https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600','15m', 41250, 95, 390, 'live', false);

-- Enable real AI generation tracking
create table if not exists generations (
  id uuid primary key default gen_random_uuid(),
  prompt text not null,
  genre text,
  status text default 'queued',
  video_url text,
  fal_request_id text,
  created_at timestamp default now()
);
